### ISSUE TITLE
Can you explain what is going on with the __k example?

### ISSUE THREAD

**Issue by MarisaKirisame** [readevalprintlove/black#5]
I had read the paper, but I still dont get it after 3 hours!

So, in my understanding, eval-var should return a value, by calling k. but k is called with an old k, so eval-var return the continuation of interpreter into the current level. It than got applied with 2, which is same as having 2 as the _ value of (+ _ 1).
The continuation getting the value return 3, but at the line of (+ _ 1), because this is the old continuation, and it than continue it's own repl loop... So the line number get reset to (+ _ 1)
But why is __k away, and why is (EM (EM 'where)) meta (instead of undefined)?

**Comment by namin** [comment]
Here is the reaction of Kenichi Asai to this example. Does it help?

> For the "where_am_i" example, here is my interpretation.  When you
>   store the current continuation to __k at (+ _ 1), what you install is
>   the continuation that has not only (+ [] 1) but also whole the rest
>   of the read-eval-print loop.  This is precisely described in the Black
>   user-observable interpreter: each level is launched with the initial
>   continuation which is the read-eval-print loop.  Thus, what is applied
>   at (__k 2) includes (+ [] 1) AND the rest of the read-eval-print loop.
>   That is why (EM where_am_i) afterwards produces "user!" in Black.

**Comment by MarisaKirisame** [comment]
I understand everything but the last line. What happend at (EM where_am_i)?

**Comment by namin** [comment]
This is how I think of it conceptually. Somehow, the captured continuation is messing up the levels, because it is captured from the meta level but called at the user level. When it's called, it launches a new user level below the user level! So now, the tower looks like user (-1 if you want), user (0), meta (1). When you call `(EM where_am_i)`, the `EM` moves from level -1 to 0. Also, `__k` is available only at level 0, because it depends on the modified `eval-var` of level 1.

Anyways, the point of this example is to show that the meta-semantics is not that intuitive, so mission accomplished :) In the upcoming POPL'18 paper with @tiarkrompf, we use a simpler meta-semantics (with only one global continuation) that better supports compiling the levels.
http://lampwww.epfl.ch/~amin/pub/collapsing-towers.pdf

**Comment by MarisaKirisame** [comment]
Havent read that paper yet, I guess I should now!
Thanks for all the help!
